// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Extend103501 {
    pub contract_account_code: String,
}

impl BinaryCodec for Extend103501 {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.contract_account_code, 6);
    }

    fn decode(buf: &mut Bytes) -> Option<Extend103501> {
        let contract_account_code = get_char_array(buf, 6)?;
        Some(Self {
            contract_account_code,
        })
    }
}

#[cfg(test)]
mod extend_103501_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_extend_103501_codec() {
        let original = Extend103501 {
            contract_account_code: vec!['a'; 6].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Extend103501::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
