// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Extend204702 {
    pub secondary_order_id: String,
}

impl BinaryCodec for Extend204702 {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.secondary_order_id, 16);
    }

    fn decode(buf: &mut Bytes) -> Option<Extend204702> {
        let secondary_order_id = get_char_array(buf, 16)?;
        Some(Self { secondary_order_id })
    }
}

#[cfg(test)]
mod extend_204702_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_extend_204702_codec() {
        let original = Extend204702 {
            secondary_order_id: vec!['a'; 16].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Extend204702::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
