// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Extend102901 {
    pub deduction_pbu: String,
    pub deduction_account_id: String,
}

impl BinaryCodec for Extend102901 {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.deduction_pbu, 6);
        put_char_array(buf, &self.deduction_account_id, 12);
    }

    fn decode(buf: &mut Bytes) -> Option<Extend102901> {
        let deduction_pbu = get_char_array(buf, 6)?;
        let deduction_account_id = get_char_array(buf, 12)?;
        Some(Self {
            deduction_pbu,
            deduction_account_id,
        })
    }
}

#[cfg(test)]
mod extend_102901_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_extend_102901_codec() {
        let original = Extend102901 {
            deduction_pbu: vec!['a'; 6].into_iter().collect::<String>(),
            deduction_account_id: vec!['a'; 12].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Extend102901::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
