// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Extend204115 {
    pub cash_margin: String,
    pub settl_type: u16,
    pub settl_period: u8,
    pub counterparty_member_id: String,
    pub counterparty_investor_type: String,
    pub counterparty_investor_id: String,
    pub counterparty_investor_name: String,
    pub counterparty_trader_code: String,
}

impl BinaryCodec for Extend204115 {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.cash_margin, 1);
        buf.put_u16(self.settl_type);
        buf.put_u8(self.settl_period);
        put_char_array(buf, &self.counterparty_member_id, 6);
        put_char_array(buf, &self.counterparty_investor_type, 2);
        put_char_array(buf, &self.counterparty_investor_id, 10);
        put_char_array(buf, &self.counterparty_investor_name, 120);
        put_char_array(buf, &self.counterparty_trader_code, 8);
    }

    fn decode(buf: &mut Bytes) -> Option<Extend204115> {
        let cash_margin = get_char_array(buf, 1)?;
        let settl_type = buf.get_u16();
        let settl_period = buf.get_u8();
        let counterparty_member_id = get_char_array(buf, 6)?;
        let counterparty_investor_type = get_char_array(buf, 2)?;
        let counterparty_investor_id = get_char_array(buf, 10)?;
        let counterparty_investor_name = get_char_array(buf, 120)?;
        let counterparty_trader_code = get_char_array(buf, 8)?;
        Some(Self {
            cash_margin,
            settl_type,
            settl_period,
            counterparty_member_id,
            counterparty_investor_type,
            counterparty_investor_id,
            counterparty_investor_name,
            counterparty_trader_code,
        })
    }
}

#[cfg(test)]
mod extend_204115_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_extend_204115_codec() {
        let original = Extend204115 {
            cash_margin: vec!['a'; 1].into_iter().collect::<String>(),
            settl_type: 1234,
            settl_period: 42,
            counterparty_member_id: vec!['a'; 6].into_iter().collect::<String>(),
            counterparty_investor_type: vec!['a'; 2].into_iter().collect::<String>(),
            counterparty_investor_id: vec!['a'; 10].into_iter().collect::<String>(),
            counterparty_investor_name: vec!['a'; 120].into_iter().collect::<String>(),
            counterparty_trader_code: vec!['a'; 8].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Extend204115::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
