// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Buf, BufMut, Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Extend200102 {
    pub stop_px: i64,
    pub min_qty: i64,
    pub max_price_levels: u16,
    pub time_in_force: String,
    pub cash_margin: String,
}

impl BinaryCodec for Extend200102 {
    fn encode(&self, buf: &mut BytesMut) {
        buf.put_i64(self.stop_px);
        buf.put_i64(self.min_qty);
        buf.put_u16(self.max_price_levels);
        put_char_array(buf, &self.time_in_force, 1);
        put_char_array(buf, &self.cash_margin, 1);
    }

    fn decode(buf: &mut Bytes) -> Option<Extend200102> {
        let stop_px = buf.get_i64();
        let min_qty = buf.get_i64();
        let max_price_levels = buf.get_u16();
        let time_in_force = get_char_array(buf, 1)?;
        let cash_margin = get_char_array(buf, 1)?;
        Some(Self {
            stop_px,
            min_qty,
            max_price_levels,
            time_in_force,
            cash_margin,
        })
    }
}

#[cfg(test)]
mod extend_200102_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_extend_200102_codec() {
        let original = Extend200102 {
            stop_px: -123456789,
            min_qty: -123456789,
            max_price_levels: 1234,
            time_in_force: vec!['a'; 1].into_iter().collect::<String>(),
            cash_margin: vec!['a'; 1].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Extend200102::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
