// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Extend201502 {
    pub share_property: String,
}

impl BinaryCodec for Extend201502 {
    fn encode(&self, buf: &mut BytesMut) {
        put_char_array(buf, &self.share_property, 2);
    }

    fn decode(buf: &mut Bytes) -> Option<Extend201502> {
        let share_property = get_char_array(buf, 2)?;
        Some(Self { share_property })
    }
}

#[cfg(test)]
mod extend_201502_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_extend_201502_codec() {
        let original = Extend201502 {
            share_property: vec!['a'; 2].into_iter().collect::<String>(),
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Extend201502::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
