// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

#[derive(Debug, Clone, PartialEq)]
pub struct Heartbeat {}

impl BinaryCodec for Heartbeat {
    fn encode(&self, _buf: &mut BytesMut) {}

    fn decode(_buf: &mut Bytes) -> Option<Heartbeat> {
        Some(Self {})
    }
}

#[cfg(test)]
mod heartbeat_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_heartbeat_codec() {
        let original = Heartbeat {};

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = Heartbeat::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
