// Code generated by fin-protoc. DO NOT EDIT.
use binary_codec::*;
use bytes::{Bytes, BytesMut};

use crate::partition_report::*;

#[derive(Debug, Clone, PartialEq)]
pub struct ReportSynchronization {
    pub partition_report: Vec<PartitionReport>,
}

impl BinaryCodec for ReportSynchronization {
    fn encode(&self, buf: &mut BytesMut) {
        put_object_list::<PartitionReport, u32>(buf, &self.partition_report);
    }

    fn decode(buf: &mut Bytes) -> Option<ReportSynchronization> {
        let partition_report = get_object_list::<PartitionReport, u32>(buf)?;
        Some(Self { partition_report })
    }
}

#[cfg(test)]
mod report_synchronization_tests {
    use super::*;
    use bytes::BytesMut;

    #[test]
    fn test_report_synchronization_codec() {
        let original = ReportSynchronization {
            partition_report: vec![],
        };

        let mut buf = BytesMut::new();
        original.encode(&mut buf);
        let mut bytes = buf.freeze();

        let decoded = ReportSynchronization::decode(&mut bytes).unwrap();
        assert_eq!(original, decoded);
    }
}
